### PR TITLE
made keep alive to be disabled or enabled in config file

### PR DESCRIPTION
**Pull request by ukcai696969**

### CODE REVIEW

**Comment by TheGamer3514** [comment]
Looks good, will be added next release

**Comment by ukcai696969** [comment]
Only added cause people are stupid and think they can configure everything in config.json which they couldn’t but can now for all the online potato’s

**Comment by ukcai696969** [comment]
THANKS ITS MERGED GO ME

**Comment by TheGamer3514** [comment]
Add more stuff

**Comment by ukcai696969** [comment]
Examples

**Pull request merged**
